### ISSUE TITLE
"Skal reserveres plass til flere inskripsjoner senere" vises ikke på utskriften

### ISSUE THREAD

**Issue by IMITromso** [Obed-AS/BaldrisPub#122]
Under "Gravmonumentbestilling" kan man krysse av for "Skal reserveres plass til flere inskripsjoner senere" og så velge antall. Dette kommer ikke frem på utskriften.

**Comment by josteinhanssen** [comment]
Blir oppdatert i neste release (helgen/begynnelse av neste uke).
