### ISSUE TITLE
Adressetype velges automatisk

### ISSUE THREAD

**Issue by josteinhanssen** [Obed-AS/BaldrisPub#4]
Der hvor det ikke er umiddelbart nødvendig med flere adresser (avdøde, referanseperson etc.) kan adressetype velges automatisk. Det er heller ikke nødvendig med listefunksjonalitet og den første adressen kan skrives inn direkte.

(Lag singleAddressComponent)

**Comment by danielehrenberg** [comment]
vet ikke om jeg helt forstod dette, hvor er det det kommer opp automatisk da?
Alle plassene jeg ser må du fortsatt velge adressetype. (men det er seint og jeg må legge meg snart.)
