### ISSUE TITLE
Forhåndsmusikk flyttes til Seremoni og endres til en checkbox

### ISSUE THREAD

**Issue by danielehrenberg** [Obed-AS/BaldrisPub#47]

**Comment by josteinhanssen** [comment]
Endret til checkbox. Lar den være på program inntil videre. Flytting vil medføre mye merarbeid mtp utskrifter.

**Comment by josteinhanssen** [comment]
Endret til checkbox. Lar den være på program inntil videre. Flytting vil medføre mye merarbeid mtp utskrifter.
