### ISSUE TITLE
Flytte "Ønker etterlatte å være tilstede" checkboxen

### ISSUE THREAD

**Issue by danielehrenberg** [Obed-AS/BaldrisPub#55]
De vil at den skal være under feks "der men velger urne" med en ja og nei checkbox.
Og at hvis "Ja" velges så tas "Assistanse til urnenedsettelse" med videre til prisoverslag som en varelinje.

Sist og minst viktig, er at hvis mulig at det genereres en hendelse for urnenedsettelse når "Ja" velges.

**Comment by josteinhanssen** [comment]
Checkbox flyttet i tidligere oppdatering. Autovarelinje følges opp i #74. Lag gjerne egen issue for den siste delen.
