### ISSUE TITLE
I utskrifter, kan ikke skrive inn eposter som ikke er i systemet.

### ISSUE THREAD

**Issue by danielehrenberg** [Obed-AS/BaldrisPub#56]
mao kan kun sende til folk i systemet, gjelder både imi tromsø og obed.

**Comment by josteinhanssen** [comment]
Dette virker så vidt jeg kan se. Man må trykke på enter tasten for at den innskrevne teksten blir lagt til. En addresse er lagt til når den er i en grå boks.

**Comment by danielehrenberg** [comment]
nope, ikke her.  den grå boksen kommer aldri

--
Med vennlig hilsen

Daniel C. Ehrenberg-Rasmussen
Grafisk designer, Piksl AS
tlf: +47 456 77 551

**Comment by josteinhanssen** [comment]
Testet i Safari, Chrome (MacOs). Samt Edge, Chrome (Windows 10). Fungerer der. Etter at e-postadressen er skrevet inn i søkefeltet må en som sagt trykke enter-tasten.

**Comment by danielehrenberg** [comment]
Ah, fuck jeg drev å tabbet eller trykket med musen.skal si fra til jon


--
Med vennlig hilsen

Daniel C. Ehrenberg-Rasmussen
Grafisk designer, Piksl AS
tlf: +47 456 77 551
