### ISSUE TITLE
Det ønskes mulighet for å manuelt sortere varer

### ISSUE THREAD

**Issue by danielehrenberg** [Obed-AS/BaldrisPub#64]
Feks: De liker ikke at når kiste skal velges så er den første som kommer opp "Barnekiste", syntes det er kleint/feil når de sitter med familie.

**Comment by josteinhanssen** [comment]
Skjønner ikke helt hvor dette er snakk om? Det er ganske mange plasser en kan velge varer...

Kister og urner er forøvrig spesialelementer i systemet og kan ha andre navn når man velger enn selve produktene. En kiste/urne i systemet kan også ha flere varelinjer tilknyttet.
