### ISSUE TITLE
Seremonioppgave, kistelapp: fdato og ddato + oppdragsnummer

### ISSUE THREAD

**Issue by josteinhanssen** [Obed-AS/BaldrisPub#7]
Seremonioppgave og kistelapp må vise både fødsels- og dødsdato. Muligens også oppdragsnummer.

**Comment by Bedemannen** [comment]
Daniel nevnte at Gravlund også kunne stå på kistelapp. Denne står allerede på Seremonioppgave

**Comment by josteinhanssen** [comment]
Har laget en egen kistelapp hvor gravlund kommer med. Så kan de som ønsker dette bruke denne og de som ønsker uten, kan bruke den dere allerede bruker. Har ikke lagt inn den nye hos dere enda...
