### ISSUE TITLE
Etasje/avdeling, henting

### ISSUE THREAD

**Issue by Sia-83** [Obed-AS/BaldrisPub#77]
Ved henting på sykehjem er det viktig å vite hvilken etasje/avdøde ligger på. Kan det legges til et felt der en kan skrive inn dette i innmelding/henting?

**Comment by josteinhanssen** [comment]
Litt usikker på hvor dette ønskes? Transport og henting/stell har allerede felter for dette?

**Comment by Sia-83** [comment]
Det er på innmeldingen. Under dødssted.

Med vennlig hilsen

Christina Stangeland Hanssen
___________________________________________
Administrerende Direktør

Obed Begravelsesbyrå
Hoveveien 38, 4306 Sandnes<x-apple-data-detectors://4>
__________________________________________

tlf: 51 68 13 00<tel:51%2068%2013%2000>
mobil: 906 75 791<tel:906%2075%20791>
e-post: christina@obed.no<mailto:christina@obed.no>
___________________________________________

Den 13. sep. 2017 kl. 10.37 skrev Jostein S. Hanssen <notifications@github.com<mailto:notifications@github.com>>:


Litt usikker på hvor dette ønskes? Transport og henting/stell har allerede felter for dette?
